server:
  port: 8016
spring:
  application:
    name: service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka