server:
  port: 8011
spring:
  application:
    name: company-server
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka,http://admin:123456@localhost:8762/eureka